kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    course: k8
    trainer: sivakumar 
spec:  
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80   ## ports no opt (automatically its taken)
