kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64mi"
        cpu: "100m"
# limits should be atleast same or more than requests i.e hard limit      
      limits:
        memory: "64mi" # minimum limits
        cpu: "100m"  