apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0dd2c9aa591ebae81